### ISSUE TITLE
Non-ASCII character

### ISSUE THREAD

**Issue by kpelechrinis** [biolab/orange3-associate#10]
I installed orange3-associate and when I try out the very first example in the tutorial document I get the following error: 

File "<stdin>", line 1, in <module>
  File "orangecontrib/associate/__init__.py", line 1, in <module>
    from .fpgrowth import \
  File "orangecontrib/associate/fpgrowth.py", line 26
SyntaxError: Non-ASCII character '\xc2' in file orangecontrib/associate/fpgrowth.py on line 27, but no encoding declared;

Any ideas?

**Comment by kernc** [comment]
The package is not compatible with Python 2. Install it in a Python 3 environment (`python3`, `pip3`) and the examples should work.
