### ISSUE TITLE
frequent_itemsets error in Oracle Linux 7

### ISSUE THREAD

**Issue by ChivasAli** [biolab/orange3-associate#19]
##### Associate version
Orange3-Associate_1.1.5

##### Orange version
`Orange.version.full_version` 3.7.0

##### Expected behavior
The command "x = frequent_itemset(list)" is supposed to return a generator object. Using the generator object, running list(x) should return a list of frequent items.

##### Actual behavior
Instead, running list(x) returns me with the error found in the following lines of code 
```
" if n_items <= _BUCKETING_FEW_ITEMS:
     return None, ((frozenset(itemset), support) for itemset, support in _bucketing_count(db, frequent_items, min_support))

/miniconda3/lib/python3.5/site-packages/orangecontrib/associate/_fpgrowth.cpython-35m-x86_64-linux-gnu.so in set.from_py.__pyx_convert_set_from_py_int (orangecontrib/associate/_fpgrowth.cpp:1399)()
TypeError: an integer is required "
```

##### Steps to reproduce the behavior
Running list(frequent_itemset(list_of_transaction)) will give this error when using Oracle Linux 7. However, it works in Windows Python

**Comment by kernc** [comment]
```py
x = frequent_itemsets(list)
```
What are you feeding it? What is `list` of?

**Comment by tijszwinkels** [comment]
I ran into this same issue.
Python 3.5
Orange3-Associate 1.1.4
Orange3 3.7.0

Test-case: https://gist.github.com/tijszwinkels/3b5561d379c72ca665df40a831d017c8#file-orange3-assoc-crash-py

**Comment by tijszwinkels** [comment]
Actually, the frequent_itemsets documentation mentions that the db should consist of array of integers. In our case, the db consisted of arrays of strings, triggering the crash.

For some reason, this doesn't seem to be enforced on windows, but it is enforced on Linux and OS X.

We converted our db to arrays of integers, and the error went away.

**Comment by leevyth** [comment]
@tijszwinkels Thank you!

**Comment by kernc** [comment]
Thanks indeed!

**Comment by ywzhang188** [comment]
> I ran into this same issue.
> Python 3.5
> Orange3-Associate 1.1.4
> Orange3 3.7.0
> Tested on both Linux(Ubuntu 16.04) and Os X.
> 
> Test-case: https://gist.github.com/tijszwinkels/3b5561d379c72ca665df40a831d017c8#file-orange3-assoc-crash-py
> 
> result:
> 
> ```
> $ python3.5 test.py 
> (frozenset({'00:00:00:00:00:273'}), 19)
> (frozenset({'00:00:00:00:00:529'}), 19)
> (frozenset({'00:00:00:00:00:273', '00:00:00:00:00:529'}), 15)
> (frozenset({'00:00:00:00:00:105'}), 19)
> Traceback (most recent call last):
>   File "test.py", line 11, in <module>
>     for x in result:
>   File "/usr/local/lib/python3.5/dist-packages/orangecontrib/associate/fpgrowth.py", line 443, in frequent_itemsets
>     yield from _fp_growth(tree, frozenset(), min_support)
>   File "/usr/local/lib/python3.5/dist-packages/orangecontrib/associate/fpgrowth.py", line 346, in _fp_growth
>     for itemsetQ, supportQ in _freq_patterns_multi(Q, alpha, min_support):
>   File "/usr/local/lib/python3.5/dist-packages/orangecontrib/associate/fpgrowth.py", line 332, in _freq_patterns_multi
>     tree, got_itemsets = _fp_tree(_prefix_paths(Q, nodes), min_support)
>   File "/usr/local/lib/python3.5/dist-packages/orangecontrib/associate/fpgrowth.py", line 260, in _fp_tree
>     for itemset, support in _bucketing_count(db, frequent_items, min_support))
>   File "assoc/_fpgrowth.pyx", line 23, in assoc._fpgrowth.bucketing_count (orangecontrib/associate/_fpgrowth.cpp:1271)
>   File "assoc/stringsource", line 123, in set.from_py.__pyx_convert_set_from_py_int (orangecontrib/associate/_fpgrowth.cpp:1399)
> TypeError: an integer is required
> ```



> Actually, the frequent_itemsets documentation mentions that the db should consist of array of integers. In our case, the db consisted of arrays of strings, triggering the crash.
> 
> For some reason, this doesn't seem to be enforced on windows, but it is enforced on Linux and OS X.
> 
> We converted our db to arrays of integers, and the error went away.

But How would you transfer strings like 'fsdafsad' into integer in Linux?

**Comment by kernc** [comment]
```py
>>> import pandas as pd
>>> pd.Categorical(['cat', 'dog', 'rat', 'cat']).codes.tolist()
[0, 1, 2, 0]
```
