### ISSUE TITLE
associate rule in Orange GUI only supports basket file?

### ISSUE THREAD

**Issue by duohappy** [biolab/orange3-associate#24]
##### Associate version

1.15

##### Orange version

3.11

##### Expected behavior
After learning about Orange association-rules help document in [http://orange3-associate.readthedocs.io/en/latest/scripting.html](http://orange3-associate.readthedocs.io/en/latest/scripting.html) , I know that 0-1 file is not supported perfectly, because it counts 0 as 'existing' items. But the function of onehot transforms 0-1 to False-True, it can get right result in python script

I try to apply association rules in Orange GUI, which is better in displaying result. I save a csv file, such as, test.csv
milk, bread, tomato, apple
True, False, True, False
False,True,False, False
...........
but it counts False as 'existing' items, which is **different from python script** and makes me so confused. I think it maybe improved.

#### Reading Orange help document
Orange supports 4 data type, Continuous, Discrete, String, Date, so it can't recognize bool type such as False-True. If I want to get right result in Orange GUI, I should use basket file, which is not so convenient.

**Comment by kernc** [comment]
How would you have it improved? Consider that you _know_ beforehand `False` (in `True` or `False`) stands for _lack_ of something. How would Orange know? Categorical (discrete) variables can have arbitrary (number of) values, such as `male`/`female`, `none`/`few`/`many`, ...

**Comment by duohappy** [comment]
@kernc ,of course, you are right, and I agree with you. Maybe, improving Orange association rules is not necessary.

The reason why I open this issue is that I can not get right result in Orange GUI after only reading help document of association rules. In help file, True-False data like that
``` python
>>> X
array([[False,  True, ...,  True, False],
       [False,  True, ...,  True, False],
       [ True, False, ..., False, False],
       ...,
       [False,  True, ...,  True, False],
       [ True, False, ..., False, False],
       [ True, False, ..., False, False]], dtype=bool)
```
I can get right result in python script, which leads me to use True-False data in Orange GUI.

Adding some description like "In Orange GUI, data file should be basket file" in help file is easier to understand.
