### ISSUE TITLE
Extract the tree before get frequent itemsets

### ISSUE THREAD

**Issue by pandikapinata** [biolab/orange3-associate#31]
How to get **tree** before process `frequent_itemsets`
Can explain the detail?
Thank you

**Comment by janezd** [comment]
This helps? https://github.com/biolab/orange3-associate/blob/master/orangecontrib/associate/fpgrowth.py

**Comment by pandikapinata** [comment]
I dont understant with that code, already call that function `_fp_tree` but got error
can u example of code use that function?
This the same issue but i still dont understand 😭 
[https://github.com/biolab/orange3-associate/issues/22]

**Comment by ajdapretnar** [comment]
Example shown in https://github.com/biolab/orange3-associate/issues/22#issuecomment-361979684.
