### ISSUE TITLE
Can't put slider on 60% on Frequent Itemsets

### ISSUE THREAD

**Issue by martijnmeeldijk** [biolab/orange3-associate#32]
##### Expected behavior
For my research, I wanted to put the slider for Minimal Support in the Frequent Itemsets widget on 60%. 

##### Actual behavior
It jumps straight from 59% to 61%. I cannot select 60%

##### Steps to reproduce the behavior
Open the Frequent Itemsets widget and adjust the Minimal Support slider.

##### Additional info (worksheets, data, screenshots, ...)

![image](https://user-images.githubusercontent.com/43355698/81484089-2e91e980-9243-11ea-86f5-da4d92685b37.png)

**Comment by kernc** [comment]
https://github.com/biolab/orange3-associate/blob/12afd273477a4b4fdcc6a2c31defd7ec4bfe5f99/orangecontrib/associate/widgets/owitemsets.py#L83-L87

Can you set it to 60% if you give it keyboard focus and press Up or Right?

**Comment by martijnmeeldijk** [comment]
Thanks for replying so fast. How do I give it keyboard focus? I tried pressing _tab_, but it will just go to the input fields. (I'm on macOS btw, maybe that helps)

**Comment by kernc** [comment]
You have to enable it, afterwards Tab will work.
https://support.apple.com/en-us/HT204434#fullkeyboard

**Comment by martijnmeeldijk** [comment]
That works perfectly, thanks. I can put the slider on 60 with my keyboard now. This solves my problem. 
It's weird that I can put it on any value perfectly with just the mouse, except for 60.
Thanks a lot

**Comment by ajdapretnar** [comment]
Fixed in #41 by simplifying sliders.
