### ISSUE TITLE
can't find associate module

### ISSUE THREAD

**Issue by muye0503** [biolab/orange3-associate#4]
I have installed the orange3-associate.

/Python/Orange/orange3env/lib/python3.4/site-packages/orangecontrib/associate$ ls
_fpgrowth.cpython-34m.so  fpgrowth.py  _fpgrowth.pyx  __init__.py  __pycache__  widgets

>>> import Orange
>>> data = Orange.data.Table("basket.tab")
>>> rules = Orange.associate.AssociationRulesSparseInducer(data, support=0.3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'associate'

**Comment by kernc** [comment]
Wherever you got `Orange.associate.AssociationRulesSparseInducer` from, it's from the old Orange 2.7 documentation. The documentation for Orange3-Associate is on RTD: http://orange3-associate.readthedocs.org/
It's used just slightly differently.
