### ISSUE TITLE
I installed, but not shows up on widgets.

### ISSUE THREAD

**Issue by adover134** [biolab/orange3-associate#53]
##### Associate version
version : 1.1.9

##### Orange version
version : 3.32.0

##### Expected behavior

After inistalling and restarting orange, the addon should be shows up on widgets.

##### Actual behavior

![Error](https://user-images.githubusercontent.com/45279353/188552311-d0bb67ed-0706-4d66-abff-81883620f8a7.png)
As you can see, I already installed Associate, but not shows up on widgets. Also, it doesn't show up on right click menu.

**Comment by adover134** [comment]
Got it... this still not supported with python 3.10.

**Comment by markotoplak** [comment]
Thanks for the reminder. I'll keep this open.
