### ISSUE TITLE
My csv file is not giving me the same output as shown in the example in the docs

### ISSUE THREAD

**Issue by yadynesh** [biolab/orange3-associate#8]
input type 1:
A,C,D,F,G,
A,B,C,D,F,
A,D,F,,,
C,D,E,,,
A,C,D,E,F,
B,C,D,E,F,G

input type 2:
A,B,C,D,E,F,G
1,0,1,1,0,1,1
1,1,1,1,0,1,0
1,0,0,1,0,1,0
0,0,1,1,1,0,0
1,0,0,1,1,1,0
0,1,1,1,1,1,1

Both of the csvs are  not working.I am getting association rules in terms of numbers. I want them to be in terms of letters

**Comment by kernc** [comment]
In order for the output to be in terms of letters, the data needs to be sparse (i.e. loaded from a basket file). File _example.basket_:
```text
A,C,D,F,G
A,B,C,D
A,D,F
C,D,E
A,C,D,E,F
B,C,D,E,F,G
```
Currently, it seems Orange regressed to not being able to read basket files.

**Comment by astaric** [comment]
The first format (basket) can be read with Orange 3.7 (and probably earlier version as well) and produces rules that consist only of letters:

<img width="410" alt="screen shot 2017-11-07 at 18 22 03" src="https://user-images.githubusercontent.com/588601/32510462-95498a2e-c3e8-11e7-965e-81a0a6c564f2.png">
