### ISSUE TITLE
Tutorial-issue

### ISSUE THREAD

**Issue by jackalhan** [biolab/orange3-associate#9]
Hello, 
I am using orange3 and orange3-assoicate in my project. I am trying to implement  following tutorial http://orange.readthedocs.io/en/latest/reference/rst/Orange.associate.html
But, the v.3 does not have the same function as in the tutorial. Can you please show us the way of doing it by using orange3-associate?
Thank you

**Comment by jackalhan** [comment]
changed topic

**Comment by kernc** [comment]
Indeed, your link appears to be a stale documentation for Orange 2. Here are the instructions for this add-on that works with Orange 3 (and is not particularly Orange-specific): https://orange3-associate.readthedocs.io/en/latest/scripting.html
